### ISSUE TITLE
Example Code for Video Data

### ISSUE THREAD

**Issue by Kyderio** [rticommunity/rticonnextdds-usecases#42]
Hi I am trying out the DDS implementation for Video Data.

However, when I try to build this example code, I am facing the below error.
![Screenshot from 2021-06-14 11-08-10](https://user-images.githubusercontent.com/71754932/121834394-474fb700-cd01-11eb-9a29-caa2b89fd842.png)

Can you help me to resolve this?

Thank you. 

Best Regards,
Kelvin

**Comment by angelrti** [comment]
The problem is that gstreamer is not found. We should either install it (https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c) or modify the `makefile.common` to point to the third-party folder instead of the system folder.

Let me know if that fixes the issue.

**Comment by Kyderio** [comment]
Hi angelrti,

I'm not sure what is causing the issue. I've tried installing gstreamer-1.0 too. 
![Screenshot from 2021-06-15 10-12-08](https://user-images.githubusercontent.com/71754932/121982502-3024ce00-cdc2-11eb-8181-e47937eeaa3b.png) 

Here is the make-common file of the example code. I commented out the system folder and point the `makefile.common` to the third-party folder.
![Screenshot from 2021-06-15 10-15-41](https://user-images.githubusercontent.com/71754932/121982687-8bef5700-cdc2-11eb-915a-99803864b326.png)

Both situations still show me that gst/gst.h is not present.

Thanks!

Best Regards,
Kelvin

**Comment by fabriziobertocci** [comment]
Kyderio,
The file gst/gst.h is part of the package libgstreamer1.0-dev (that appears
to be installed in your system).
To verify, use this command:
dpkg -L libgstreamer1.0-dev
or:
apt-file list libstreamer1.0-dev
It shows the gstreamer headers are installed under:
/usr/include/gstreamer-1.0

As a first step, can you please verify you have that directory in your
system (and has not been deleted/moved by mistake or by another conflicting
package)?

Also, in your makefile.common, it seems the -I/usr/include/gstreamer-1.0
(plus all the other directories but they are irrelevant), is commented out:
#-I/usr/include/gstreamer-1.0 \
...
Just make sure that directory is part of the include search path. (from
your original email it seems it is included, but double check again please).

Regards,
Fabrizio

**Comment by Kyderio** [comment]
Hi,

It would seem that I have (permanently) deleted the directory `/usr/include/gstreamer-1.0` by accident.

Is there any way to get them back? 

I have tried 

```bash 
apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
```
I have all these installed. What else should I do to properly install gstreamer?

Thanks for all the assistance.

Best Regards,
Kelvin

**Comment by fabriziobertocci** [comment]
You need to install the package libgstreamer-1.0*-dev:*
apt reinstall libgstreamer-1.0-dev

Regards,
Fabrizio

**Comment by Kyderio** [comment]
Hi,

Im using Ubuntu 20.04. 

![Screenshot from 2021-06-15 15-16-35](https://user-images.githubusercontent.com/71754932/122009362-97577800-cdec-11eb-9b65-aec97aeb3c05.png)

Thanks so much in advance!

Best Regards,
Kelvin

**Comment by Kyderio** [comment]
Hi,

New update, somehow I managed to reinstall and get the gst files.

Can I double check if this is the expected output for running `make -f make/Makefile.x64Linux4gcc7.3.0`? 
![Screenshot from 2021-06-15 17-50-43](https://user-images.githubusercontent.com/71754932/122032661-6da94b80-ce02-11eb-9909-17f751146345.png)

However, when i try to run the examples, it doesn't seem to run for me.

![Screenshot from 2021-06-15 17-55-36](https://user-images.githubusercontent.com/71754932/122033086-ca0c6b00-ce02-11eb-900e-a10a4b1d2562.png)

May I check with you if I am missing anything?

Thank you.

Best Regards,
Kelvin

**Comment by angelrti** [comment]
It seems that you have to add the architecture when calling the script, can you try the following?
`./scripts/VideoPublisher.sh x64Linux4gcc7.3.0`

**Comment by Kyderio** [comment]
Hi,

I am facing the error shown in the picture below. Similar error occur for running the Video subscriber script too.

![Screenshot from 2021-06-15 18-45-44](https://user-images.githubusercontent.com/71754932/122039988-e19b2200-ce09-11eb-803f-ed086821aa9b.png)

Thank you.

Best Regards,
Kelvin

**Comment by angelrti** [comment]
Hi Kyderio,

It seems that the installation of RTI Connext DDS doesn't find the corresponding license file. Can you double-check that you have it correctly installed?
For doing that, you can open RTI Launcher, go to the tab "Configuration" and check that the "License Information" box is pointing to the correct license file. If it does, you can click on the 'Details' button to see what might be wrong.

If that doesn't help, you may want to contact your sales team at: https://www.rti.com/company/contact

I hope this helps,
Angel.

**Comment by Kyderio** [comment]
I see, it is working now thanks!
