### ISSUE TITLE
Syntax error in StartRouterTCPWAN.sh

### ISSUE THREAD

**Issue by pwolf15** [rticommunity/rticonnextdds-usecases#46]
Missing “-“ specifier in StartRouterTCPWAN script.

https://github.com/rticommunity/rticonnextdds-usecases/blob/367f11f23918d802612232fc2a93e2eb3e12ab72/DataSubsetWAN/ExampleCode/scripts/StartRouterTCPWAN.sh#L9

For last check (n == 3), should be `[ -n "$3" ]`

**Comment by juanlu-rti** [comment]
Opened branch issues/46 for fixing.
