### ISSUE TITLE
Bad Link for Video Data Use Case

### ISSUE THREAD

**Issue by tbrownrti** [rticommunity/rticonnextdds-usecases#48]
Link is bad : [rticonnextdds-usecases/VideoData at master · rticommunity/rticonnextdds-usecases](https://github.com/rticommunity/rticonnextdds-usecases/tree/master/VideoData)  .  

This page offers a link for "Detailed documentation and how-to videos for this example are available online" at: https://www.rti.com/resources/usecases/streaming-video, which results in a Page Not Found error. 

Should be replaced with correct link here: [Real-Time Video Data Streaming](https://www.rti.com/developers/case-code/video-data-streaming)

**Comment by angelrti** [comment]
fixed as part of #45
